[[redirects]]
from = "https://vease.geode-solutions.netlify.com/*"
to = "https://vease.geode-solutions.com/:splat"
status = 301
force = true

[build]
base = "app"
publish = "../dist"
ignore = "exit 0"

[functions]
directory = "../.netlify/functions-internal"

[context.production]
command = "cd .. && sed -i 's/\"0\\.0\\.0\"/\"latest\"/g' package.json && cat package.json && npm i && npm list && npm run build"

[context.branch-deploy]
command = "cd .. && sed -i 's/\"0\\.0\\.0\"/\"next\"/g' package.json && cat package.json && npm i && npm list && npm run build"