// Generated by opengeodeweb-microservice-generate, do not edit.
import type json from "./vease_schemas.json";

export interface ControllerCommandsStreamParams {}

export interface ControllerCommandsStreamResponse {
  response: any;
  statusCode: number;
}

export interface ControllerCommandsReplyParams {
  error?: string;
  ok: boolean;
  requestId: string;
  result?: any;
}

export interface ControllerCommandsReplyResponse {
  response: ControllerCommandsReplyResponseResponse;
  statusCode: number;
}

export interface ControllerCommandsReplyResponseResponse {}

export interface ControllerDataManageParams {
  action: ControllerDataManageParamsAction;
  id: string;
  name?: string;
}

export type ControllerDataManageParamsAction = "rename" | "delete";

export interface ControllerDataManageResponse {
  response: any;
  statusCode: number;
}

export interface ControllerDataLoadParams {}

export interface ControllerDataLoadResponse {
  response: any;
  statusCode: number;
}

export interface ControllerDataListParams {}

export interface ControllerDataListResponse {
  response: any;
  statusCode: number;
}

export interface ControllerDataDetailsParams {
  id: string;
}

export interface ControllerDataDetailsResponse {
  response: any;
  statusCode: number;
}

export interface ControllerDataCreateParams {
  closed?: boolean;
  kind: ControllerDataCreateParamsKind;
  name: string;
  points: Array<number[]>;
}

export type ControllerDataCreateParamsKind = "point" | "curve" | "surface";

export interface ControllerDataCreateResponse {
  response: any;
  statusCode: number;
}

export interface ControllerFilesUploadParams {
  token: string;
}

export interface ControllerFilesUploadResponse {
  response: ControllerFilesUploadResponseResponse;
  statusCode: number;
}

export interface ControllerFilesUploadResponseResponse {}

export interface ControllerFilesDownloadParams {
  token: string;
}

export interface ControllerFilesDownloadResponse {
  response: any;
  statusCode: number;
}

export interface ControllerFilterApplyParams {
  attribute?: string;
  factor?: number;
  filter: Filter;
  ids: string[];
  item?: number;
  location?: ControllerFilterApplyParamsLocation;
  maximum?: number;
  minimum?: number;
  planes?: Plane[];
  remove?: boolean;
  slices?: Slice[];
}

export type Filter = "shrink" | "explode" | "slice" | "clip" | "threshold";

export type ControllerFilterApplyParamsLocation =
  | "vertex"
  | "edge"
  | "cell"
  | "polygon"
  | "polyhedron"
  | "point";

export interface Plane {
  normal: number[];
  origin: number[];
}

export interface Slice {
  axis: number;
  index: number;
}

export interface ControllerFilterApplyResponse {
  response: any;
  statusCode: number;
}

export interface ControllerExportParams {
  filePath: string;
  includeBackground?: boolean;
  kind: ControllerExportParamsKind;
}

export type ControllerExportParamsKind = "screenshot" | "project";

export interface ControllerExportResponse {
  response: ControllerExportResponseResponse;
  statusCode: number;
}

export interface ControllerExportResponseResponse {
  filePath: string;
}

export interface ControllerColormapsParams {}

export interface ControllerColormapsResponse {
  response: ControllerColormapsResponseResponse;
  statusCode: number;
}

export interface ControllerColormapsResponseResponse {
  categories: { [key: string]: string[] };
}

export interface ControllerStyleSetParams {
  color?: string;
  coloring?: Coloring;
  componentIds?: string[];
  id: string;
  size?: number;
  target?: Target;
  visibility?: boolean;
  width?: number;
}

export type Coloring = "constant" | "random" | "textures";

export type Target =
  | "points"
  | "edges"
  | "cells"
  | "polygons"
  | "polyhedra"
  | "corners"
  | "lines"
  | "surfaces"
  | "blocks";

export interface ControllerStyleSetResponse {
  response: any;
  statusCode: number;
}

export interface ControllerStyleAttributeParams {
  attribute: string;
  colormap?: string;
  componentIds?: string[];
  id: string;
  item?: number;
  location?: ControllerStyleAttributeParamsLocation;
  maximum?: number;
  minimum?: number;
  noDataColor?: string;
  target?: Target;
  timeStep?: number;
}

export type ControllerStyleAttributeParamsLocation =
  | "vertex"
  | "edge"
  | "cell"
  | "polygon"
  | "polyhedron";

export interface ControllerStyleAttributeResponse {
  response: any;
  statusCode: number;
}

export interface ControllerViewSetParams {
  action: ControllerViewSetParamsAction;
  axes?: boolean;
  backgroundColor?: string;
  componentIds?: string[];
  grid?: boolean;
  id?: string;
  name?: string;
  orientation?: Orientation;
  positionId?: number;
  zScaling?: number;
}

export type ControllerViewSetParamsAction =
  | "reset"
  | "focus"
  | "orient"
  | "save"
  | "restore"
  | "scene";

export type Orientation = "xplus" | "xminus" | "yplus" | "yminus" | "zplus" | "zminus";

export interface ControllerViewSetResponse {
  response: any;
  statusCode: number;
}

export interface ControllerViewerStateParams {}

export interface ControllerViewerStateResponse {
  response: any;
  statusCode: number;
}

export interface LlmStatusParams {}

export interface LlmStatusResponse {
  running: boolean;
  statusCode: number;
}

export interface LlmRunParams {
  model?: string;
}

export interface LlmRunResponse {
  apiKey: string;
  port: number;
  statusCode: number;
}

export interface LlmKillParams {}

export interface LlmKillResponse {
  statusCode: number;
}

export interface LlmChatParams {
  gatewayApiKey?: string;
  messages: { [key: string]: any }[];
  model?: string;
  provider?: string;
  [property: string]: any;
}

export interface ErrorResponse {
  code: number;
  description: string;
  name: string;
}

// `__params` and `__response` only exist at type level, to infer request/response types from a schema.
// A type alias (not an interface) keeps the implicit index signature of the JSON type it is intersected with.
export type TypedSchema<Params, Response> = {
  readonly __params?: Params;
  readonly __response?: Response;
};

export interface Schemas {
  readonly api: {
    readonly controller: {
      readonly commands: {
        readonly stream: (typeof json)["api"]["controller"]["commands"]["stream"] &
          TypedSchema<ControllerCommandsStreamParams, ControllerCommandsStreamResponse>;
        readonly reply: (typeof json)["api"]["controller"]["commands"]["reply"] &
          TypedSchema<ControllerCommandsReplyParams, ControllerCommandsReplyResponse>;
      };
      readonly data: {
        readonly manage: (typeof json)["api"]["controller"]["data"]["manage"] &
          TypedSchema<ControllerDataManageParams, ControllerDataManageResponse>;
        readonly load: (typeof json)["api"]["controller"]["data"]["load"] &
          TypedSchema<ControllerDataLoadParams, ControllerDataLoadResponse>;
        readonly list: (typeof json)["api"]["controller"]["data"]["list"] &
          TypedSchema<ControllerDataListParams, ControllerDataListResponse>;
        readonly details: (typeof json)["api"]["controller"]["data"]["details"] &
          TypedSchema<ControllerDataDetailsParams, ControllerDataDetailsResponse>;
        readonly create: (typeof json)["api"]["controller"]["data"]["create"] &
          TypedSchema<ControllerDataCreateParams, ControllerDataCreateResponse>;
      };
      readonly files: {
        readonly upload: (typeof json)["api"]["controller"]["files"]["upload"] &
          TypedSchema<ControllerFilesUploadParams, ControllerFilesUploadResponse>;
        readonly download: (typeof json)["api"]["controller"]["files"]["download"] &
          TypedSchema<ControllerFilesDownloadParams, ControllerFilesDownloadResponse>;
      };
      readonly filter: {
        readonly apply: (typeof json)["api"]["controller"]["filter"]["apply"] &
          TypedSchema<ControllerFilterApplyParams, ControllerFilterApplyResponse>;
      };
      readonly export: (typeof json)["api"]["controller"]["export"] &
        TypedSchema<ControllerExportParams, ControllerExportResponse>;
      readonly colormaps: (typeof json)["api"]["controller"]["colormaps"] &
        TypedSchema<ControllerColormapsParams, ControllerColormapsResponse>;
      readonly style: {
        readonly set: (typeof json)["api"]["controller"]["style"]["set"] &
          TypedSchema<ControllerStyleSetParams, ControllerStyleSetResponse>;
        readonly attribute: (typeof json)["api"]["controller"]["style"]["attribute"] &
          TypedSchema<ControllerStyleAttributeParams, ControllerStyleAttributeResponse>;
      };
      readonly view: {
        readonly set: (typeof json)["api"]["controller"]["view"]["set"] &
          TypedSchema<ControllerViewSetParams, ControllerViewSetResponse>;
      };
      readonly viewer: {
        readonly state: (typeof json)["api"]["controller"]["viewer"]["state"] &
          TypedSchema<ControllerViewerStateParams, ControllerViewerStateResponse>;
      };
    };
    readonly llm: {
      readonly status: (typeof json)["api"]["llm"]["status"] &
        TypedSchema<LlmStatusParams, LlmStatusResponse>;
      readonly run: (typeof json)["api"]["llm"]["run"] & TypedSchema<LlmRunParams, LlmRunResponse>;
      readonly kill: (typeof json)["api"]["llm"]["kill"] &
        TypedSchema<LlmKillParams, LlmKillResponse>;
      readonly chat: (typeof json)["api"]["llm"]["chat"] & TypedSchema<LlmChatParams, Blob>;
    };
  };
}

declare const schemas: Schemas;
export default schemas;
