// Generated by opengeodeweb-microservice-generate, do not edit.
import type json from "./vease_schemas.json";

export interface ControllerCommandsStreamParams {}

export interface ControllerCommandsStreamResponse {
  response: any;
  statusCode: number;
}

export interface ControllerCommandsReplyParams {
  error?: string;
  ok: boolean;
  requestId: string;
  result?: any;
}

export interface ControllerCommandsReplyResponse {
  response: ControllerCommandsReplyResponseResponse;
  statusCode: number;
}

export interface ControllerCommandsReplyResponseResponse {}

export interface ControllerDataLoadParams {}

export interface ControllerDataLoadResponse {
  response: any;
  statusCode: number;
}

export interface ControllerDataListParams {}

export interface ControllerDataListResponse {
  response: any;
  statusCode: number;
}

export interface ControllerDataDetailsParams {
  id: string;
}

export interface ControllerDataDetailsResponse {
  response: any;
  statusCode: number;
}

export interface ControllerColormapsParams {}

export interface ControllerColormapsResponse {
  response: ControllerColormapsResponseResponse;
  statusCode: number;
}

export interface ControllerColormapsResponseResponse {
  categories: { [key: string]: string[] };
}

export interface ControllerStyleSetParams {
  color?: string;
  coloring?: Coloring;
  componentIds?: string[];
  id: string;
  size?: number;
  target?: Target;
  visibility?: boolean;
  width?: number;
}

export type Coloring = "constant" | "random" | "textures";

export type Target =
  | "points"
  | "edges"
  | "cells"
  | "polygons"
  | "polyhedra"
  | "corners"
  | "lines"
  | "surfaces"
  | "blocks";

export interface ControllerStyleSetResponse {
  response: any;
  statusCode: number;
}

export interface ControllerStyleAttributeParams {
  attribute: string;
  colormap?: string;
  componentIds?: string[];
  id: string;
  item?: number;
  location?: Location;
  maximum?: number;
  minimum?: number;
  noDataColor?: string;
  target?: Target;
  timeStep?: number;
}

export type Location = "vertex" | "edge" | "cell" | "polygon" | "polyhedron";

export interface ControllerStyleAttributeResponse {
  response: any;
  statusCode: number;
}

export interface ControllerViewerMeshPointsVisibilityParams {
  id: string;
  visibility: boolean | number | string;
}

export interface ControllerViewerMeshPointsVisibilityResponse {
  response: ControllerViewerMeshPointsVisibilityResponseResponse;
  statusCode: number;
}

export interface ControllerViewerMeshPointsVisibilityResponseResponse {
  id: string;
  visibility: boolean;
}

export interface ControllerViewerStateParams {}

export interface ControllerViewerStateResponse {
  response: any;
  statusCode: number;
}

export interface ControllerViewerRenderParams {}

export interface ControllerViewerRenderResponse {
  response: ControllerViewerRenderResponseResponse;
  statusCode: number;
}

export interface ControllerViewerRenderResponseResponse {}

export interface LlmStatusParams {}

export interface LlmStatusResponse {
  running: boolean;
  statusCode: number;
}

export interface LlmRunParams {
  model?: string;
}

export interface LlmRunResponse {
  apiKey: string;
  port: number;
  statusCode: number;
}

export interface LlmKillParams {}

export interface LlmKillResponse {
  statusCode: number;
}

export interface LlmChatParams {
  gatewayApiKey?: string;
  messages: { [key: string]: any }[];
  model?: string;
  provider?: string;
  [property: string]: any;
}

export interface ErrorResponse {
  code: number;
  description: string;
  name: string;
}

// `__params` and `__response` only exist at type level, to infer request/response types from a schema.
// A type alias (not an interface) keeps the implicit index signature of the JSON type it is intersected with.
export type TypedSchema<Params, Response> = {
  readonly __params?: Params;
  readonly __response?: Response;
};

export interface Schemas {
  readonly api: {
    readonly controller: {
      readonly commands: {
        readonly stream: (typeof json)["api"]["controller"]["commands"]["stream"] &
          TypedSchema<ControllerCommandsStreamParams, ControllerCommandsStreamResponse>;
        readonly reply: (typeof json)["api"]["controller"]["commands"]["reply"] &
          TypedSchema<ControllerCommandsReplyParams, ControllerCommandsReplyResponse>;
      };
      readonly data: {
        readonly load: (typeof json)["api"]["controller"]["data"]["load"] &
          TypedSchema<ControllerDataLoadParams, ControllerDataLoadResponse>;
        readonly list: (typeof json)["api"]["controller"]["data"]["list"] &
          TypedSchema<ControllerDataListParams, ControllerDataListResponse>;
        readonly details: (typeof json)["api"]["controller"]["data"]["details"] &
          TypedSchema<ControllerDataDetailsParams, ControllerDataDetailsResponse>;
      };
      readonly colormaps: (typeof json)["api"]["controller"]["colormaps"] &
        TypedSchema<ControllerColormapsParams, ControllerColormapsResponse>;
      readonly style: {
        readonly set: (typeof json)["api"]["controller"]["style"]["set"] &
          TypedSchema<ControllerStyleSetParams, ControllerStyleSetResponse>;
        readonly attribute: (typeof json)["api"]["controller"]["style"]["attribute"] &
          TypedSchema<ControllerStyleAttributeParams, ControllerStyleAttributeResponse>;
      };
      readonly viewer: {
        readonly mesh: {
          readonly points: {
            readonly visibility: (typeof json)["api"]["controller"]["viewer"]["mesh"]["points"]["visibility"] &
              TypedSchema<
                ControllerViewerMeshPointsVisibilityParams,
                ControllerViewerMeshPointsVisibilityResponse
              >;
          };
        };
        readonly state: (typeof json)["api"]["controller"]["viewer"]["state"] &
          TypedSchema<ControllerViewerStateParams, ControllerViewerStateResponse>;
        readonly render: (typeof json)["api"]["controller"]["viewer"]["render"] &
          TypedSchema<ControllerViewerRenderParams, ControllerViewerRenderResponse>;
      };
    };
    readonly llm: {
      readonly status: (typeof json)["api"]["llm"]["status"] &
        TypedSchema<LlmStatusParams, LlmStatusResponse>;
      readonly run: (typeof json)["api"]["llm"]["run"] & TypedSchema<LlmRunParams, LlmRunResponse>;
      readonly kill: (typeof json)["api"]["llm"]["kill"] &
        TypedSchema<LlmKillParams, LlmKillResponse>;
      readonly chat: (typeof json)["api"]["llm"]["chat"] & TypedSchema<LlmChatParams, Blob>;
    };
  };
}

declare const schemas: Schemas;
export default schemas;
