// Generated by opengeodeweb-microservice-generate, do not edit.
import type json from "./vease_schemas.json";

export interface ControllerDataLoadParams {}

export interface ControllerDataLoadResponse {
  response: any;
  statusCode: number;
}

export interface ControllerViewerMeshPointsVisibilityParams {
  id: string;
  visibility: boolean | number | string;
}

export interface ControllerViewerMeshPointsVisibilityResponse {
  response: any;
  statusCode: number;
}

export interface ControllerViewerRenderParams {}

export interface ControllerViewerRenderResponse {
  response: any;
  statusCode: number;
}

export interface LlmStatusParams {}

export interface LlmStatusResponse {
  running: boolean;
  statusCode: number;
}

export interface LlmRunParams {
  model?: string;
}

export interface LlmRunResponse {
  apiKey: string;
  port: number;
  statusCode: number;
}

export interface LlmKillParams {}

export interface LlmKillResponse {
  statusCode: number;
}

export interface LlmChatParams {
  gatewayApiKey?: string;
  messages: { [key: string]: any }[];
  model?: string;
  provider?: string;
  [property: string]: any;
}

export interface ErrorResponse {
  code: number;
  description: string;
  name: string;
}

// `__params` and `__response` only exist at type level, to infer request/response types from a schema.
// A type alias (not an interface) keeps the implicit index signature of the JSON type it is intersected with.
export type TypedSchema<Params, Response> = {
  readonly __params?: Params;
  readonly __response?: Response;
};

export interface Schemas {
  readonly api: {
    readonly controller: {
      readonly data: {
        readonly load: (typeof json)["api"]["controller"]["data"]["load"] &
          TypedSchema<ControllerDataLoadParams, ControllerDataLoadResponse>;
      };
      readonly viewer: {
        readonly mesh: {
          readonly points: {
            readonly visibility: (typeof json)["api"]["controller"]["viewer"]["mesh"]["points"]["visibility"] &
              TypedSchema<
                ControllerViewerMeshPointsVisibilityParams,
                ControllerViewerMeshPointsVisibilityResponse
              >;
          };
        };
        readonly render: (typeof json)["api"]["controller"]["viewer"]["render"] &
          TypedSchema<ControllerViewerRenderParams, ControllerViewerRenderResponse>;
      };
    };
    readonly llm: {
      readonly status: (typeof json)["api"]["llm"]["status"] &
        TypedSchema<LlmStatusParams, LlmStatusResponse>;
      readonly run: (typeof json)["api"]["llm"]["run"] & TypedSchema<LlmRunParams, LlmRunResponse>;
      readonly kill: (typeof json)["api"]["llm"]["kill"] &
        TypedSchema<LlmKillParams, LlmKillResponse>;
      readonly chat: (typeof json)["api"]["llm"]["chat"] & TypedSchema<LlmChatParams, Blob>;
    };
  };
}

declare const schemas: Schemas;
export default schemas;
