name: Playwright Tests
on:
  push:
    branches: [ fix/*, feature/* ]
  pull_request:
    branches: [ master, next ]

jobs:
  test-e2e:
    timeout-minutes: 20
    runs-on: [ ubuntu-latest, windows-latest ]
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Package the project
      run: npm run build_microservices && npm run package
    - name: Run Playwright tests
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 5
