name: Playwright Tests
on:
  push:
    branches: [ fix/*, feature/* ]
  pull_request:
    branches: [ master, next ]

env:
  GITHUB_TOKEN: ${{ secrets.TOKEN }}

jobs:
  test-e2e:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest ]
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Install dependencies
      run: npm i
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Package the project
      run: |
        dotnet tool install --global AzureSignTool --version 4.0.1
        npm run install_microservices
        npm run build_microservices
        npm run package
      env:
        AZURE_KEY_VAULT_URI: ${{ secrets.AZURE_KEY_VAULT_URI }}
        AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        AZURE_CERT_NAME: ${{ secrets.AZURE_CERT_NAME }}
    - name: Linux set screen resolution
      if: matrix.os == 'ubuntu-latest'
      run: xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24"
    - name: Run Playwright tests
      run: npm run test_e2e
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 5
