name: Test

on:
  push:
    branches-ignore:
      - master
      - next

jobs:
  test:
    uses: Geode-solutions/actions/.github/workflows/js-test.yml@master
    with:
      repos: ${{ vars.REPOS }}
    secrets: inherit

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: Geode-solutions/actions/install/checkout@master
        with:
          token: ${{ secrets.TOKEN }}
      - name: Install dependencies
        uses: Geode-solutions/actions/install/node-dependencies@master
        with:
          repos: ${{ vars.REPOS }}
          branch: ${{ github.ref_name }}
          use_registry: false
          token: ${{ secrets.TOKEN }}
      - name: Typecheck
        run: npm run typecheck
